slides:
	jupyter-nbconvert --to slides B*.ipynb --SlidesExporter.reveal_theme=solarized --SlidesExporter.reveal_scroll=True  --SlidesExporter.reveal_transition=fade

sync:
	rsync -av --del --exclude=".git/" . ~/nextcloud/yanfei.site/bde




